package com.roomwire.protocol

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import org.junit.jupiter.api.fail
import java.io.File
import java.math.BigDecimal
import java.math.RoundingMode

/**
 * protocol/transcripts.txt is generated by driving the Swift state machines
 * through scripted scenarios and recording every answer. This replays the same
 * inputs against the Kotlin machines and insists on the same answers, character
 * for character.
 *
 * The scenarios are not re-scripted here. That is the point: the vectors test
 * has to duplicate every construction in both languages and trusts the two
 * lists to be the same list; this reads the inputs off the file. One set of
 * scenarios, one owner (the file), and a port cannot pass by testing something
 * subtly different from what Swift tested.
 *
 * Numbers compare at six decimals. Both sides are IEEE binary64 doing the same
 * operations in the same order, so a difference at that precision is logic —
 * a threshold moved, a comparison flipped — not rounding.
 */
class TranscriptsTest {

    @TestFactory
    fun transcripts(): List<DynamicTest> {
        val file = File(System.getProperty("transcripts") ?: "../../protocol/transcripts.txt")
        assertTrue(file.isFile, "transcripts.txt not found at ${file.absolutePath}")

        val rows = file.readLines().filter { it.isNotBlank() && !it.startsWith("#") }.map { line ->
            val f = line.split("\t")
            assertEquals(5, f.size, "malformed transcript line: $line")
            Row(f[0], f[1], f[2], f[3], f[4], line)
        }
        // A short read must fail loudly rather than pass over half the machines.
        assertEquals(327, rows.size, "expected 327 steps, parsed ${rows.size}")
        assertEquals(
            setOf(
                "chaingate", "pacer", "cursor", "pointer", "touch",
                "reassembler", "replay", "opener", "framing",
            ),
            rows.map { it.machine }.toSet(),
            "every machine must appear — a missing one is an unported file",
        )

        // One test per scenario, replayed in order on a fresh instance.
        return rows.groupBy { it.machine to it.scenario }.map { (key, steps) ->
            DynamicTest.dynamicTest("${key.first} / ${key.second}") {
                val replay = replayer(key.first)
                for (s in steps) {
                    val actual = replay.step(s.op, args(s.args))
                    assertEquals(s.expected, actual, "${s.machine}/${s.scenario}  ${s.op} ${s.args}\n  line: ${s.line}")
                }
            }
        }
    }

    private data class Row(val machine: String, val scenario: String, val op: String, val args: String, val expected: String, val line: String)

    private fun args(s: String): Map<String, String> =
        if (s == "-") emptyMap() else s.split(" ").associate { kv -> kv.substringBefore("=") to kv.substringAfter("=") }

    private fun replayer(machine: String): Replayer = when (machine) {
        "chaingate" -> ChainGateReplay()
        "pacer" -> PacerReplay()
        "cursor" -> CursorReplay()
        "pointer" -> PointerReplay()
        "touch" -> TouchReplay()
        "reassembler" -> ReassemblerReplay()
        "replay" -> ReplayWindowReplay()
        "opener" -> OpenerReplay()
        "framing" -> FramingReplay()
        else -> fail("no replayer for machine '$machine'")
    }

    private interface Replayer { fun step(op: String, a: Map<String, String>): String }

    private class ChainGateReplay : Replayer {
        val g = ChainGate()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> {
                val v = g.admit(a.u16("seq"), a.u16("base"), a.flag("droppable"), a.flag("restores"))
                "${verdict(v)} ${state()}"
            }
            "reset" -> { g.reset(); state() }
            else -> fail("chaingate: unknown op $op")
        }
        fun state() = "broken=${g.isBroken.bit} missing=${g.missing} missingBase=${g.missingBase}"
        fun verdict(v: ChainGate.Verdict) = when (v) {
            ChainGate.Verdict.DECODE -> "decode"; ChainGate.Verdict.BROKEN -> "broken"; ChainGate.Verdict.STALE -> "stale"
        }
    }

    private class PacerReplay : Replayer {
        val p = Pacer()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> {
                val (v, late) = p.admit(a.d("remote"), a.d("now"))
                val vs = when (v) {
                    is Pacer.Verdict.Present -> "present:${f(v.after)}"
                    Pacer.Verdict.ShowNow -> "showNow"
                    Pacer.Verdict.DecodeOnly -> "decodeOnly"
                }
                "$vs late=${f(late)}"
            }
            "use" -> {
                p.use(if (a["mode"] == "control") Pacer.Mode.CONTROL else Pacer.Mode.WATCH)
                "-"
            }
            else -> fail("pacer: unknown op $op")
        }
    }

    private class CursorReplay : Replayer {
        val c = CursorTrack()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "arrived" -> { c.arrived(a.u32("sentMs"), Point(a.d("x"), a.d("y")), a.d("now")); "-" }
            "position" -> c.position(a.d("now"))?.let { pt(it) } ?: "nil"
            "idle" -> c.idle(a.d("now")).toString()
            "isEmpty" -> c.isEmpty.toString()
            "clear" -> { c.clear(); "-" }
            else -> fail("cursor: unknown op $op")
        }
    }

    private class PointerReplay : Replayer {
        val p = PointerState()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> actions(p.admit(a.u8("buttons"), Point(a.d("x"), a.d("y")), a.d("now")))
            "release" -> actions(p.release(a.d("now")))
            else -> fail("pointer: unknown op $op")
        }
        fun button(b: PointerState.Button) = if (b == PointerState.Button.LEFT) "left" else "right"
        fun actions(out: List<PointerState.Action>) =
            if (out.isEmpty()) "-" else out.joinToString(";") {
                when (it) {
                    is PointerState.Action.Move -> "move(${pt(it.at)})"
                    is PointerState.Action.Drag -> "drag(${pt(it.at)},${button(it.button)})"
                    is PointerState.Action.Down -> "down(${pt(it.at)},${button(it.button)},${it.clicks})"
                    is PointerState.Action.Up -> "up(${pt(it.at)},${button(it.button)},${it.clicks})"
                }
            }
    }

    private class TouchReplay : Replayer {
        val t = TouchIntent()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> steps(t.admit(phase(a.getValue("phase")), Point(a.d("x"), a.d("y"))))
            "holdFired" -> steps(t.holdFired())
            "awaitingHold" -> t.awaitingHold.toString()
            else -> fail("touch: unknown op $op")
        }
        fun phase(s: String) = when (s) {
            "began" -> TouchIntent.Phase.BEGAN; "moved" -> TouchIntent.Phase.MOVED
            "ended" -> TouchIntent.Phase.ENDED; "cancelled" -> TouchIntent.Phase.CANCELLED
            else -> fail("touch: unknown phase $s")
        }
        fun steps(out: List<TouchIntent.Step>) =
            if (out.isEmpty()) "-" else out.joinToString(";") { "step(${it.buttons},${pt(it.at)})" }
    }

    private class ReassemblerReplay : Replayer {
        val r = Reassembler()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "absorb" -> {
                // Byte k of slice `index` of frame `id` is (id + index + k) & 0xFF,
                // as on the Swift side, so the sum is a check on what came out.
                val id = a.u32("frame")
                val index = a.u16("index")
                val body = ByteArray(a.getValue("len").toInt()) { k -> (id.toLong() + index.toInt() + k).toByte() }
                val h = ChunkHeader.Fields(ChunkHeader.Kind.VIDEO, 0uL, id, index, a.u16("count"))
                r.absorb(h, body, a.d("now"))?.let { "delivered len=${it.size} sum=${digest(it)}" } ?: "nil"
            }
            else -> fail("reassembler: unknown op $op")
        }
    }

    private class ReplayWindowReplay : Replayer {
        val w = ReplayWindow()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> if (w.admit(a.getValue("counter").toULong())) "accept" else "reject"
            else -> fail("replay: unknown op $op")
        }
    }

    /**
     * The ordering rule, replayed: bounds, then the tag, then the replay
     * window. The forgedSprayThenReal scenario is the one that matters — five
     * forged datagrams must not consume the counters they claim, or an attacker
     * sending nothing but noise blacks out the stream.
     */
    private class OpenerReplay : Replayer {
        val key = ByteArray(32) { it.toByte() }
        var role: MediaSeal.Role? = null
        var o: MediaSeal.Opener? = null
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "open" -> {
                // The role is on every line, and the first one makes the opener:
                // a scenario is one end of one lane for its whole length.
                val want = if (a.getValue("role") == "host") MediaSeal.Role.HOST else MediaSeal.Role.VIEWER
                if (o == null) { role = want; o = MediaSeal.Opener(key, want) }
                check(role == want) { "an opener changed role mid-scenario" }
                val counter = a.getValue("counter").toULong()
                val tamper = a.getValue("tamper")
                val len = a.getValue("len").toInt()
                val body = ByteArray(len) { (counter.toLong() + it).toByte() }
                val fields = ChunkHeader.Fields(ChunkHeader.Kind.VIDEO, counter, 1u, 0u, 1u)
                // The lane comes from the file as a literal, never derived
                // from the role here: deriving it would use the same mapping
                // the Opener uses and cancel out a mistake in exactly that
                // mapping. The contract says which lane the bytes are on.
                val d = MediaSeal.seal(fields, body, key, a.getValue("lane").toUInt())
                if (tamper == "tag") d[d.size - 1] = (d[d.size - 1].toInt() xor 1).toByte()
                if (tamper == "header") d[9] = (d[9].toInt() xor 1).toByte()
                o!!.open(d)?.let {
                    "delivered counter=${it.first.counter} len=${it.second.size} sum=${digest(it.second)}"
                } ?: "refused"
            }
            else -> fail("opener: unknown op $op")
        }
    }

    private class FramingReplay : Replayer {
        val d = Framing.Decoder()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "feed" -> {
                val hex = a.getValue("bytes")
                val bytes = ByteArray(hex.length / 2) { hex.substring(it * 2, it * 2 + 2).toInt(16).toByte() }
                d.feed(bytes)?.let { frames ->
                    if (frames.isEmpty()) "none"
                    else frames.joinToString(";") { "frame len=${it.size} sum=${digest(it)}" }
                } ?: "violation"
            }
            else -> fail("framing: unknown op $op")
        }
    }

    private companion object {
        /**
         * Order-sensitive on purpose. A plain byte sum is not: a reassembler
         * that concatenates slices in *arrival* order rather than index order
         * passes every line in the file exactly, while handing the decoder
         * scrambled H.264.
         */
        fun digest(b: ByteArray): Int = b.fold(0) { s, x -> (s * 31 + (x.toInt() and 0xFF)) and 0xFFFF }

        /**
         * Six decimals, rounded half-even on the exact binary value — which is
         * what C's printf does on the Swift side. String.format would round
         * half-up on a decimal approximation instead; the two agree on every
         * value in the file today and would disagree on an exact tie tomorrow.
         */
        fun f(v: Double): String = BigDecimal(v).setScale(6, RoundingMode.HALF_EVEN).toPlainString()
        fun pt(p: Point) = "${f(p.x)},${f(p.y)}"
        val Boolean.bit get() = if (this) 1 else 0
        fun Map<String, String>.d(k: String) = getValue(k).toDouble()
        fun Map<String, String>.u8(k: String) = getValue(k).toUByte()
        fun Map<String, String>.u16(k: String) = getValue(k).toUShort()
        fun Map<String, String>.u32(k: String) = getValue(k).toUInt()
        fun Map<String, String>.flag(k: String) = getValue(k) == "1"
    }
}
