import Foundation

// The wire format, frozen as bytes, so a second implementation can be held to
// it. Run with: ./check.sh
//
// Packet.swift is about to stop being the only implementation of this protocol:
// an Android viewer speaks it too, in Kotlin. Two implementations of one format
// drift — not loudly, but as a coordinate that is off by a rounding, or a
// message that one side refuses and the other waves through. That is discovered
// months later as a corrupt frame on somebody's phone, and by then neither side
// looks wrong on its own.
//
// So the bytes become the specification and neither language owns them. This
// emits every message type as hex on stdout; check.sh diffs the result against
// protocol/vectors.txt and fails if it moved. Changing the wire format is then
// a deliberate act that shows up as a diff in a checked-in file, rather than
// something a refactor can do by accident.
//
// The file sits at the top level rather than under android/ on purpose: it
// belongs to the protocol, not to either implementation of it. Swift generates
// it, Kotlin reads it, and a third client would read the same copy.
//
// Three verdicts, because a decoder has two jobs and one of them is refusing:
//
//   ENCODE  the named construction must produce exactly these bytes, and they
//           must decode back. The inputs live in both languages; the bytes live
//           here. Inputs drifting apart is exactly what a byte mismatch catches.
//   ACCEPT  a decoder must accept these bytes. For shapes we never encode but
//           must still read.
//   REJECT  a decoder must refuse these bytes. Every one of these is a bug that
//           was reasoned about once; a second implementation does not get to
//           rediscover them the hard way.
//
// This file asserts both directions on the Swift side as it goes, so a vector
// that is wrong here never reaches the Kotlin port claiming to be truth.

@main
enum PacketVectors {
    static var lines: [String] = []

    static func main() {
        video()
        pointer()
        marks()
        viewerReports()
        control()
        hostile()

        print("# ExtendPilot wire format, generated by Checks/PacketVectors.swift.")
        print("# Do not hand-edit: run ./check.sh, which regenerates and diffs this.")
        print("# name<TAB>verdict<TAB>hex   verdicts: ENCODE, ACCEPT, REJECT")
        for line in lines { print(line) }
    }

    // MARK: - Video, ids 0 and 1

    static let sps = Data([0x67, 0x64, 0x00, 0x1f])
    static let pps = Data([0x68, 0xeb, 0xe3, 0xcb])
    static let payload = Data([0x00, 0x00, 0x00, 0x05, 0x65, 0x01, 0x02, 0x03, 0x04])

    static func video() {
        encode("video.keyframe",
               Packet.encode(payload: payload, sps: sps, pps: pps, keyframe: true,
                             sentMs: 0xA1B2C3D4, sequence: 41, baseSequence: 20))

        // Recovery: restarts a broken chain, so a viewer sitting on a gap may
        // decode it. Sequence at its wrap point on purpose.
        encode("video.delta.recovery",
               Packet.encode(payload: payload, sps: nil, pps: nil, keyframe: false,
                             recovery: true, sentMs: 7, sequence: 0xFFFF, baseSequence: 0xFFFE))

        encode("video.delta.ltr",
               Packet.encode(payload: payload, sps: nil, pps: nil, keyframe: false,
                             sentMs: 9, sequence: 3, baseSequence: 2,
                             ltrToken: 0xDEAD_BEEF_CAFE_F00D))

        // The enhancement layer: nothing is built on it, so losing it costs
        // only itself. baseSequence stays behind the frame it hangs off.
        encode("video.delta.droppable",
               Packet.encode(payload: payload, sps: nil, pps: nil, keyframe: false,
                             droppable: true, sentMs: 11, sequence: 8, baseSequence: 4))

        // A keyframe with parameter sets AND a token — the first frame after a
        // decoder failure on a link that has LTR working.
        encode("video.keyframe.ltr",
               Packet.encode(payload: payload, sps: sps, pps: pps, keyframe: true,
                             sentMs: 0x0000_0001, sequence: 0, baseSequence: 0,
                             ltrToken: 1))

        // Marker 7: every defined bit at once. We never send this — a keyframe
        // is never droppable — but a decoder must read it rather than refuse it,
        // because 7 is the boundary the guard is written against.
        var all = Data([0])
        all.append(contentsOf: [0, 0, 0, 22])          // sentMs
        all.append(7)                                   // ltr | recovery | droppable
        all.append(contentsOf: [0, 0, 0, 0, 0, 0, 0, 5])  // token
        all.append(contentsOf: [0, 9])                  // sequence
        all.append(contentsOf: [0, 8])                  // baseSequence
        all.append(contentsOf: [0, 0, 0, 0])            // no SPS
        all.append(contentsOf: [0, 0, 0, 0])            // no PPS
        all.append(contentsOf: [0xAA])                  // payload
        accept("video.marker.allBitsSet", all)

        // Parameter sets are independent lengths, so a frame may carry one.
        encode("video.keyframe.spsOnly",
               Packet.encode(payload: payload, sps: sps, pps: nil, keyframe: true,
                             sentMs: 2, sequence: 1, baseSequence: 1))
    }

    // MARK: - Pointer, ids 2 and 3

    static func pointer() {
        encode("cursor", Packet.encodeCursor(seq: 0x1234, sentMs: 0x89AB_CDEF, x: 0.25, y: 0.75))
        // The corners, because a normalized coordinate's whole job is surviving
        // a difference in resolution between the two ends.
        encode("cursor.topLeft", Packet.encodeCursor(seq: 0, sentMs: 0, x: 0, y: 0))
        encode("cursor.bottomRight", Packet.encodeCursor(seq: 0xFFFF, sentMs: 0xFFFF_FFFF, x: 1, y: 1))
        encode("cursorHidden", Packet.encodeCursorHidden(seq: 0x0102))
    }

    // MARK: - Marks and reactions, ids 4 to 6

    static func marks() {
        encode("mark.point", Packet.encodeMark(.point, x: 0.5, y: 0.5))
        encode("mark.draw", Packet.encodeMark(.draw, x: 0.125, y: 0.875))
        encode("mark.lift", Packet.encodeMark(.lift, x: 1, y: 0))
        encode("mark.clear", Packet.encodeMark(.clear, x: 0, y: 1))

        // Encode clamps rather than refuses: a coordinate this far out is our
        // own arithmetic overshooting, not a hostile peer.
        encode("mark.clamped.high", Packet.encodeMark(.point, x: 7, y: 3))
        encode("mark.clamped.low", Packet.encodeMark(.point, x: -2, y: -0.5))

        encode("relayedMark.slot0", Packet.encodeRelayedMark(slot: 0, kind: .draw, x: 0.25, y: 0.5))
        encode("relayedMark.slot7", Packet.encodeRelayedMark(slot: 7, kind: .point, x: 0.75, y: 0.25))

        for r in Packet.Reaction.allCases {
            encode("reaction.\(r)", Packet.encodeReaction(r))
        }
    }

    // MARK: - What a viewer reports back, ids 7 and 10 to 13

    static func viewerReports() {
        encode("telemetry", Packet.encodeTelemetry(frames: 1800, kilobytes: 40_000, maxGapMs: 250,
                                                   p95GapMs: 45, skipped: 12, gapDropped: 3))
        // Every field saturates rather than wraps: a count that wrapped would
        // read as a link that healed.
        encode("telemetry.clamped", Packet.encodeTelemetry(frames: Int.max, kilobytes: Int.max,
                                                           maxGapMs: Int.max, p95GapMs: Int.max,
                                                           skipped: Int.max, gapDropped: Int.max))

        encode("needKeyframe", Packet.needKeyframeMessage)
        encode("needRefresh", Packet.needRefreshMessage)
        encode("identify", Packet.identifyMessage)
        encode("ackReference", Packet.encodeAckReference(token: 0xDEAD_BEEF_CAFE_F00D))

        encode("flight.empty", Packet.encodeFlight([]))
        encode("flight.three", Packet.encodeFlight([
            .init(sequence: 100, latenessMs: 0, flags: Packet.FlightRecord.shown),
            .init(sequence: 101, latenessMs: -35, flags: Packet.FlightRecord.skipped),
            .init(sequence: 102, latenessMs: 0x7FFF,
                  flags: Packet.FlightRecord.gapDropped | Packet.FlightRecord.keyframe),
        ]))
        // Sixty records in, forty-eight out, and it is the newest that survive:
        // the analysis wants the texture of the last second, not its beginning.
        encode("flight.capped", Packet.encodeFlight((0 ..< 60).map {
            .init(sequence: UInt16($0), latenessMs: Int16($0), flags: Packet.FlightRecord.shown)
        }))

        encode("probe.two", Packet.encodeProbe([
            .init(drawn: true, ms: 1000, x: 0, y: 1, seq: 5),
            .init(drawn: false, ms: 1016, x: 0.5, y: 0.25, seq: 6),
        ]))
        // The probe is the one path that turns a coordinate into an Int, which
        // is where a NaN traps rather than merely being wrong — clamping does
        // not remove it. Infinities do clamp, so only NaN needed the guard.
        // Both ends must agree that it reads as zero.
        encode("probe.hostileCoordinates", Packet.encodeProbe([
            .init(drawn: true, ms: 1, x: .nan, y: .infinity, seq: 1),
            .init(drawn: false, ms: 2, x: -.infinity, y: .nan, seq: 2),
        ]))
    }

    // MARK: - Control, ids 14 to 18

    static func control() {
        // buttons is the whole state, not an edge — bit0 left, bit1 right — so
        // a lost message is corrected by the next rather than leaving a button
        // held down on the presenter's Mac.
        encode("input.noButtons", Packet.encodeInput(buttons: 0, x: 0.5, y: 0.5))
        encode("input.left", Packet.encodeInput(buttons: 1, x: 0.1, y: 0.2))
        encode("input.right", Packet.encodeInput(buttons: 2, x: 0.3, y: 0.4))
        encode("input.both", Packet.encodeInput(buttons: 3, x: 1, y: 1))
        // Encode masks the undefined bits away; decode refuses them. The two
        // are deliberately not symmetric.
        encode("input.maskedToThree", Packet.encodeInput(buttons: 0xFF, x: 0, y: 0))

        encode("scroll.positive", Packet.encodeScroll(dx: 120, dy: 45))
        encode("scroll.negative", Packet.encodeScroll(dx: -120, dy: -45))
        encode("scroll.extremes", Packet.encodeScroll(dx: Int16.min, dy: Int16.max))

        encode("requestControl", Packet.requestControlMessage)
        encode("controlGranted.true", Packet.encodeControlGranted(true))
        encode("controlGranted.false", Packet.encodeControlGranted(false))

        for g in Packet.SystemGesture.allCases {
            encode("systemGesture.\(g)", Packet.encodeSystemGesture(g))
        }
    }

    // MARK: - Everything a decoder has to refuse

    static func hostile() {
        // A coordinate off the unit square would park a layer at infinity, and
        // now also confines an injected click to the screen being shared.
        reject("mark.nan", Data([4, 0]) + be32(0x7FC0_0000) + be32(0))
        reject("mark.infinity", Data([4, 0]) + be32(0x7F80_0000) + be32(0))
        reject("mark.negativeInfinity", Data([4, 0]) + be32(0xFF80_0000) + be32(0))
        reject("mark.aboveOne", Data([4, 0]) + be32(0x3FC0_0000) + be32(0))   // 1.5
        reject("mark.belowZero", Data([4, 0]) + be32(0xBF80_0000) + be32(0))  // -1.0
        reject("cursor.nan", Data([2, 0, 0, 0, 0, 0, 0]) + be32(0x7FC0_0000) + be32(0))
        reject("input.nan", Data([14, 0]) + be32(0x7FC0_0000) + be32(0))

        // Values outside a fixed set. Guessing at what a peer meant is not an
        // option while it is holding the presenter's mouse.
        reject("mark.unknownKind", Data([4, 99]) + be32(0) + be32(0))
        reject("relayedMark.unknownKind", Data([5, 0, 99]) + be32(0) + be32(0))
        reject("reaction.unknown", Data([6, 99]))
        reject("systemGesture.unknown", Data([18, 99]))
        reject("controlGranted.notABoolean", Data([17, 2]))
        reject("input.undefinedButton", Data([14, 4]) + be32(0) + be32(0))

        // Marker bits past the three defined ones.
        var badMarker = Packet.encode(payload: payload, sps: nil, pps: nil, keyframe: false,
                                      sentMs: 9, sequence: 3, baseSequence: 2, ltrToken: 1)
        badMarker[5] = 8
        reject("video.unknownMarkerBit", badMarker)

        // A length header that overruns the buffer, trusted, is a read past the
        // end. Refused instead.
        //
        // The padding is load-bearing and both of these vectors were wrong
        // without it. decode's first guard is a 19-byte minimum, so a shorter
        // frame is refused on length before the lying-length check is ever
        // reached — the vector passed while testing nothing at all. Same below:
        // that frame carries an SPS purely to clear the minimum, so the guard
        // it is named for is the one that actually refuses it.
        reject("video.lyingSpsLength",
               Data([1, 0, 0, 0, 0, 0, 0, 9, 0, 4]) + be32(0x7FFF_FFFF)
                   + Data(repeating: 0xAB, count: 6))

        // A frame that decodes to nothing is not a frame.
        reject("video.emptyPayload",
               Data([1, 0, 0, 0, 0, 0, 0, 9, 0, 4]) + be32(1) + Data([0x67]) + be32(0))

        // A prefix of a real frame must return nil rather than crash. The cuts
        // below walk the header: short of the minimum, inside the LTR token,
        // inside the sequence pair, inside the SPS length, inside SPS itself,
        // inside the PPS length, inside PPS, and exactly at the end of the
        // parameter sets — which leaves no payload, and a frame that decodes to
        // nothing is not a frame.
        let ltr = Packet.encode(payload: payload, sps: sps, pps: pps, keyframe: true,
                                sentMs: 5, sequence: 1, baseSequence: 1, ltrToken: 2)
        for n in [4, 10, 16, 20, 24, 28, 32, 34] {
            reject("video.truncated.\(n)", ltr.prefix(n))
        }

        // But truncation *inside the payload* is not detectable, and a second
        // implementation must agree that it is not. Every other field declares
        // its length; the payload is simply whatever remains, so losing bytes
        // off the end of it reads as a smaller frame rather than a damaged one.
        // Nothing here can change that — the guard against it is one layer down,
        // where a truncated access unit fails to decode as H.264.
        accept("video.truncatedPayload.isIndistinguishable", ltr.prefix(ltr.count - 1))

        // Fixed-length messages are checked with ==, so overlong is as wrong as
        // short. A trailing byte means the sender and we disagree about the
        // format, and the disagreement is not ours to resolve.
        reject("cursorHidden.short", Data([3, 1]))
        reject("cursorHidden.long", Data([3, 1, 2, 3]))
        reject("needKeyframe.long", Data([8, 0]))
        reject("needRefresh.long", Data([11, 0]))
        reject("identify.long", Data([9, 0]))
        reject("requestControl.long", Data([16, 0]))
        reject("ackReference.short", Data([10, 1, 2, 3, 4, 5, 6, 7]))
        reject("ackReference.long", Data([10, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
        reject("scroll.short", Data([15, 0, 1, 0]))
        reject("scroll.long", Data([15, 0, 1, 0, 2, 0]))
        reject("telemetry.short", Data([7]) + Data(repeating: 0, count: 19))
        reject("reaction.long", Data([6, 0, 0]))
        reject("mark.short", Data([4, 0]) + be32(0) + Data([0, 0, 0]))

        // Batched messages declare their own count. The cap is the wire format,
        // not a suggestion, and the declared count must match the bytes present.
        reject("flight.countPastCap", Data([12, 49]) + Data(repeating: 0, count: 49 * 5))
        reject("flight.countDisagreesWithLength", Data([12, 3]) + Data(repeating: 0, count: 5))
        reject("probe.countPastCap", Data([13, 65]) + Data(repeating: 0, count: 65 * 11))
        reject("probe.countDisagreesWithLength", Data([13, 2]) + Data(repeating: 0, count: 11))
        // 0 = drawn, 1 = arrived. There is no third timeline.
        reject("probe.unknownTimeline", Data([13, 1, 7]) + Data(repeating: 0, count: 10))

        // Nothing is allocated past 18 yet. An unknown id must not be mistaken
        // for the nearest one that happens to be the right length.
        reject("id.unallocated19", Data([19, 1]))
        reject("id.unallocated200", Data([200]))
        reject("id.empty", Data())
    }

    // MARK: - Plumbing

    static func encode(_ name: String, _ data: Data) {
        guard Packet.decodeMessage(data) != nil else {
            fatalError("\(name): this vector does not decode on the Swift side, so it is not truth")
        }
        lines.append("\(name)\tENCODE\t\(hex(data))")
    }

    static func accept(_ name: String, _ data: Data) {
        guard Packet.decodeMessage(data) != nil else {
            fatalError("\(name): expected to be accepted, but the Swift decoder refused it")
        }
        lines.append("\(name)\tACCEPT\t\(hex(data))")
    }

    static func reject(_ name: String, _ data: Data) {
        guard Packet.decodeMessage(data) == nil else {
            fatalError("\(name): expected to be refused, but the Swift decoder accepted it")
        }
        lines.append("\(name)\tREJECT\t\(hex(data))")
    }

    static func be32(_ v: UInt32) -> Data {
        Data([UInt8(truncatingIfNeeded: v >> 24), UInt8(truncatingIfNeeded: v >> 16),
              UInt8(truncatingIfNeeded: v >> 8), UInt8(truncatingIfNeeded: v)])
    }

    static func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }
}
