import CoreGraphics
import Foundation

// The four state machines, frozen as behaviour, so a second implementation can
// be held to them. Run with: ./check.sh
//
// protocol/vectors.txt pins the wire format as bytes. That is the right shape
// for an encoder — the same input must produce the same bytes — but ChainGate,
// Pacer, CursorTrack and the pointer contract are not encoders. They are
// decisions over time: a verdict that depends on every frame before it, a hold
// that widens when a link degrades, a tap that becomes a drag ten points later.
// Bytes cannot express "and then". A transcript can.
//
// So this drives each machine through scripted scenarios and prints every step
// as a line: what was asked, and what the Swift implementation answered. The
// Kotlin side does not re-script the scenarios — it replays the inputs from
// this file and asserts its own answers match, character for character. One
// set of scenarios, written once, and neither language owns the answers.
//
// Numbers are printed to six decimal places. Both languages implement IEEE
// binary64 with the same operations in the same order, so a difference at that
// precision is a difference in logic — a threshold moved, a comparison flipped,
// an operation reordered — not rounding. Which is exactly the drift this exists
// to catch.
//
// Format:  machine<TAB>scenario<TAB>op<TAB>args<TAB>result
// A new scenario name means a fresh instance. Points are x,y.

@main
enum TranscriptVectors {
    static var lines: [String] = []

    static func main() {
        chainGate()
        pacer()
        cursor()
        pointer()
        touch()

        print("# RoomLink behaviour transcripts, generated by swift/Checks/TranscriptVectors.swift.")
        print("# Do not hand-edit: run ./check.sh, which regenerates and diffs this.")
        print("# machine<TAB>scenario<TAB>op<TAB>args<TAB>result   a new scenario is a fresh instance")
        for line in lines { print(line) }
    }

    // MARK: - ChainGate

    static func chainGate() {
        var g = ChainGate()
        var scenario = ""
        func fresh(_ name: String) { g = ChainGate(); scenario = name }
        func admit(_ seq: UInt16, _ base: UInt16, droppable: Bool = false, restores: Bool = false) {
            let v = g.admit(sequence: seq, baseSequence: base, droppable: droppable, restores: restores)
            emit("chaingate", scenario, "admit",
                 "seq=\(seq) base=\(base) droppable=\(droppable ? 1 : 0) restores=\(restores ? 1 : 0)",
                 "\(verdict(v)) broken=\(g.isBroken ? 1 : 0) missing=\(g.missing) missingBase=\(g.missingBase)")
        }
        func reset() {
            g.reset()
            emit("chaingate", scenario, "reset", "-",
                 "broken=\(g.isBroken ? 1 : 0) missing=\(g.missing) missingBase=\(g.missingBase)")
        }
        func verdict(_ v: ChainGate.Verdict) -> String {
            switch v { case .decode: return "decode"; case .broken: return "broken"; case .stale: return "stale" }
        }

        // A keyframe opens the chain; base and enhancement frames alternate.
        fresh("steady")
        admit(1, 1, restores: true)
        admit(2, 2)
        admit(3, 2, droppable: true)
        admit(4, 3)
        admit(5, 3, droppable: true)
        admit(6, 4)

        // Losing an enhancement frame costs exactly that frame.
        fresh("enhancementLoss")
        admit(1, 1, restores: true)
        admit(2, 2)
        // seq 3 (droppable, base 2) never arrives
        admit(4, 3)
        admit(5, 3, droppable: true)

        // Losing a base frame breaks it, and a recovery frame reopens it.
        fresh("baseLoss")
        admit(1, 1, restores: true)
        admit(2, 2)
        // seq 3 (base 3) never arrives
        admit(4, 4)
        admit(5, 4, droppable: true)
        admit(6, 5)
        admit(7, 6, restores: true)
        admit(8, 7)

        // The counters wrap at 16 bits and nothing notices.
        fresh("wrap")
        admit(0xFFFE, 0xFFFE, restores: true)
        admit(0xFFFF, 0xFFFF)
        admit(0x0000, 0x0000)
        admit(0x0001, 0x0000, droppable: true)
        admit(0x0002, 0x0001)

        // A packet that turns up late is stale, not ~65,000 losses.
        fresh("reorder")
        admit(1, 1, restores: true)
        admit(2, 2)
        admit(4, 3)   // arrives before 3
        admit(3, 3)   // late
        admit(5, 4)

        // The same frame twice invents no loss.
        fresh("duplicate")
        admit(1, 1, restores: true)
        admit(2, 2)
        admit(2, 2)
        admit(3, 3)

        // An enhancement frame built on an older base is stale; on the current
        // base, fine; on a base not yet seen, evidence of loss.
        fresh("enhancementBases")
        admit(1, 1, restores: true)
        admit(2, 2)
        admit(3, 3)
        admit(4, 2, droppable: true)   // built on a base already superseded
        admit(5, 3, droppable: true)   // built on the current base
        admit(6, 5, droppable: true)   // built on one that never came

        // Before any keyframe there is no chain to be part of.
        fresh("beforeAnyChain")
        admit(1, 1)
        admit(2, 2)
        admit(3, 3, restores: true)
        admit(4, 4)
        reset()
        admit(5, 5)
    }

    // MARK: - Pacer

    static func pacer() {
        var p = Pacer()
        var scenario = ""
        func fresh(_ name: String) { p = Pacer(); scenario = name }
        func admit(_ remote: TimeInterval, _ now: TimeInterval) {
            let remote = q(remote), now = q(now)
            let r = p.admit(remote: remote, now: now)
            let v: String
            switch r.verdict {
            case .present(let after): v = "present:\(f(after))"
            case .showNow: v = "showNow"
            case .decodeOnly: v = "decodeOnly"
            }
            emit("pacer", scenario, "admit", "remote=\(f(remote)) now=\(f(now))", "\(v) late=\(f(r.lateness))")
        }

        // A fixed one-second transit: every frame lands in its slot.
        fresh("onSchedule")
        for i in 0 ..< 5 { let t = Double(i) / 30; admit(t, t + 1) }

        // Jitter inside the hold is absorbed by it.
        fresh("jitter")
        admit(0, 1)
        admit(0.033, 1.033 + 0.05)
        admit(0.066, 1.066 + 0.02)
        admit(0.1, 1.1 + 0.11)
        admit(0.133, 1.133)

        // A stall delivers its backlog all at once: one frame surfaces, the
        // rest decode silently, and every 300 ms another surfaces.
        fresh("burst")
        admit(0, 1)
        for i in 1 ..< 14 { admit(Double(i) / 30, 2) }
        admit(0.5, 2.3)
        admit(0.533, 2.3)
        admit(0.566, 2.61)

        // Lateness that holds for two seconds is the link's new floor.
        fresh("floor")
        admit(0, 1)
        admit(0.1, 1.5)
        admit(0.2, 2.0)
        admit(0.3, 2.5)
        admit(0.4, 3.0)
        admit(0.5, 3.5)   // lateSince + 2.0 reached
        admit(0.533, 3.533)

        // Travelled faster than the anchor frame: adopt it.
        fresh("fasterThanAnchor")
        admit(0, 1)
        admit(0.1, 1.05)
        admit(0.2, 1.15)

        // Lateness past thirty seconds is a clock, not a network.
        fresh("clockBroke")
        admit(0, 1)
        admit(0.1, 40)
        admit(0.2, 40.1)
    }

    // MARK: - CursorTrack

    static func cursor() {
        var c = CursorTrack()
        var scenario = ""
        func fresh(_ name: String) { c = CursorTrack(); scenario = name }
        func arrived(_ sentMs: UInt32, _ x: Double, _ y: Double, _ now: TimeInterval) {
            let x = q(x), y = q(y), now = q(now)
            c.arrived(sentMs: sentMs, at: CGPoint(x: x, y: y), now: now)
            emit("cursor", scenario, "arrived", "sentMs=\(sentMs) x=\(f(x)) y=\(f(y)) now=\(f(now))", "-")
        }
        func position(_ now: TimeInterval) {
            let now = q(now)
            let p = c.position(now: now)
            emit("cursor", scenario, "position", "now=\(f(now))", p.map { pt($0) } ?? "nil")
        }
        func idle(_ now: TimeInterval) {
            let now = q(now)
            emit("cursor", scenario, "idle", "now=\(f(now))", c.idle(now: now) ? "true" : "false")
        }
        func isEmpty() { emit("cursor", scenario, "isEmpty", "-", c.isEmpty ? "true" : "false") }
        func clear() { c.clear(); emit("cursor", scenario, "clear", "-", "-") }

        // Nothing yet; then one position, held until the next arrives.
        fresh("firstArrival")
        position(5)
        isEmpty()
        arrived(1000, 0.1, 0.2, 5)
        isEmpty()
        position(5)
        position(5.03)
        position(5.2)

        // A metronome at 16 ms with perfect transit: positions interpolate
        // between two the hand really visited.
        fresh("steadyGlide")
        arrived(1000, 0.10, 0.50, 5.000)
        arrived(1016, 0.20, 0.50, 5.016)
        arrived(1032, 0.30, 0.50, 5.032)
        arrived(1048, 0.40, 0.50, 5.048)
        position(5.050)
        position(5.058)
        position(5.066)
        position(5.074)
        position(5.082)
        position(5.098)
        position(5.300)

        // One packet lands 100 ms late: the hold widens to meet it and the
        // mapping creeps rather than jumps.
        fresh("latePacket")
        arrived(1000, 0.1, 0.1, 5.000)
        arrived(1016, 0.2, 0.1, 5.016)
        arrived(1032, 0.3, 0.1, 5.132)
        arrived(1048, 0.4, 0.1, 5.048)
        arrived(1064, 0.5, 0.1, 5.064)
        position(5.100)
        position(5.150)
        position(5.200)
        position(5.250)

        // A packet that travelled faster than the anchor is believed at once.
        fresh("fasterPacket")
        arrived(1000, 0.1, 0.1, 5.000)
        arrived(1016, 0.2, 0.1, 5.006)
        arrived(1032, 0.3, 0.1, 5.022)
        position(5.060)
        position(5.070)

        // The 32-bit stamp rolls over and the pointer does not strand.
        fresh("wrap")
        arrived(0xFFFF_FFF0, 0.1, 0.1, 5.000)
        arrived(0x0000_0000, 0.2, 0.1, 5.016)
        arrived(0x0000_0010, 0.3, 0.1, 5.032)
        position(5.060)
        position(5.070)

        // A stamp far behind the origin is a restarted clock, not a late packet.
        fresh("clockJump")
        arrived(50000, 0.1, 0.1, 5.000)
        arrived(1000, 0.9, 0.9, 5.016)
        position(5.016)
        position(5.100)

        // Idle once the buffer is spent and nothing new has come; clear empties it.
        fresh("idleAndClear")
        idle(5)
        arrived(1000, 0.1, 0.1, 5.000)
        idle(5.1)
        idle(5.6)
        clear()
        isEmpty()
        position(5.7)
    }

    // MARK: - PointerState: mask -> events

    static func pointer() {
        var p = PointerState()
        var scenario = ""
        func fresh(_ name: String) { p = PointerState(); scenario = name }
        func admit(_ buttons: UInt8, _ x: Double, _ y: Double, _ now: TimeInterval) {
            let x = q(x), y = q(y), now = q(now)
            let out = p.admit(buttons: buttons, at: CGPoint(x: x, y: y), now: now)
            emit("pointer", scenario, "admit", "buttons=\(buttons) x=\(f(x)) y=\(f(y)) now=\(f(now))", actions(out))
        }
        func release(_ now: TimeInterval) {
            let now = q(now)
            emit("pointer", scenario, "release", "now=\(f(now))", actions(p.release(now: now)))
        }
        func button(_ b: PointerState.Button) -> String { b == .left ? "left" : "right" }
        func actions(_ a: [PointerState.Action]) -> String {
            if a.isEmpty { return "-" }
            return a.map { action in
                switch action {
                case .move(let at): return "move(\(pt(at)))"
                case .drag(let at, let b): return "drag(\(pt(at)),\(button(b)))"
                case .down(let at, let b, let clicks): return "down(\(pt(at)),\(button(b)),\(clicks))"
                case .up(let at, let b, let clicks): return "up(\(pt(at)),\(button(b)),\(clicks))"
                }
            }.joined(separator: ";")
        }

        let L = PointerState.left, R = PointerState.right

        // The first message is always a move; then a click.
        fresh("moveAndClick")
        admit(0, 10, 10, 0)
        admit(0, 10, 10, 0.05)
        admit(L, 10, 10, 0.1)
        admit(0, 10, 10, 0.2)

        // Near enough and soon enough counts up, and caps at three.
        fresh("doubleAndTripleClick")
        admit(L, 10, 10, 0)
        admit(0, 10, 10, 0.05)
        admit(L, 12, 11, 0.3)
        admit(0, 12, 11, 0.35)
        admit(L, 12, 11, 0.6)
        admit(0, 12, 11, 0.65)
        admit(L, 12, 11, 0.9)
        admit(0, 12, 11, 0.95)

        // Too far, or too late, and it is a single click again.
        fresh("notDouble")
        admit(L, 10, 10, 0)
        admit(0, 10, 10, 0.05)
        admit(L, 20, 10, 0.3)     // 10 points away
        admit(0, 20, 10, 0.35)
        admit(L, 20, 10, 1.0)     // 0.65 s later
        admit(0, 20, 10, 1.05)

        // Movement while held is a drag, never a move.
        fresh("drag")
        admit(L, 0, 0, 0)
        admit(L, 5, 5, 0.1)
        admit(L, 40, 40, 0.2)
        admit(0, 40, 40, 0.3)

        // Both buttons at once, in the order the mask is read.
        fresh("bothButtons")
        admit(L | R, 3, 3, 0)
        admit(L | R, 6, 6, 0.1)
        admit(0, 6, 6, 0.2)

        // The right button never counts clicks.
        fresh("rightClick")
        admit(R, 5, 5, 0)
        admit(0, 5, 5, 0.1)
        admit(R, 5, 5, 0.2)
        admit(0, 5, 5, 0.3)

        // A viewer that vanished mid-drag: whatever is held is released where it stands.
        fresh("releaseVanished")
        release(0)
        admit(L, 8, 8, 0)
        admit(L, 30, 30, 0.1)
        release(0.2)
        release(0.3)
    }

    // MARK: - TouchIntent: finger -> mask

    static func touch() {
        var t = TouchIntent()
        var scenario = ""
        func fresh(_ name: String) { t = TouchIntent(); scenario = name }
        func phase(_ ph: TouchIntent.Phase) -> String {
            switch ph { case .began: return "began"; case .moved: return "moved"; case .ended: return "ended"; case .cancelled: return "cancelled" }
        }
        func admit(_ ph: TouchIntent.Phase, _ x: Double, _ y: Double) {
            let x = q(x), y = q(y)
            let out = t.admit(ph, at: CGPoint(x: x, y: y))
            emit("touch", scenario, "admit", "phase=\(phase(ph)) x=\(f(x)) y=\(f(y))", steps(out))
        }
        func holdFired() { emit("touch", scenario, "holdFired", "-", steps(t.holdFired())) }
        func awaitingHold() { emit("touch", scenario, "awaitingHold", "-", t.awaitingHold ? "true" : "false") }
        func steps(_ s: [TouchIntent.Step]) -> String {
            s.isEmpty ? "-" : s.map { "step(\($0.buttons),\(pt($0.at)))" }.joined(separator: ";")
        }

        // A quick lift is a click, at the finger.
        fresh("tap")
        awaitingHold()
        admit(.began, 5, 5)
        awaitingHold()
        admit(.ended, 5, 5)
        awaitingHold()

        // A hold is a right click, and the lift then owes nothing.
        fresh("hold")
        admit(.began, 5, 5)
        holdFired()
        awaitingHold()
        holdFired()
        admit(.ended, 5, 5)

        // Movement past the slop is a drag, pressed where the finger started.
        fresh("drag")
        admit(.began, 0, 0)
        admit(.moved, 3, 3)
        awaitingHold()
        admit(.moved, 20, 20)
        awaitingHold()
        admit(.moved, 25, 25)
        holdFired()
        admit(.ended, 30, 30)

        // Cancelled: a drag lifts, a tap vanishes.
        fresh("cancelled")
        admit(.began, 0, 0)
        admit(.cancelled, 0, 0)
        admit(.began, 0, 0)
        admit(.moved, 20, 20)
        admit(.cancelled, 20, 20)

        // Nothing without a beginning; the hold does not fire after a drag.
        fresh("orphans")
        admit(.moved, 5, 5)
        admit(.ended, 5, 5)
        holdFired()
        admit(.began, 0, 0)
        admit(.moved, 20, 20)
        holdFired()
        admit(.ended, 20, 20)
    }

    // MARK: - Plumbing

    static func emit(_ machine: String, _ scenario: String, _ op: String, _ args: String, _ result: String) {
        lines.append("\(machine)\t\(scenario)\t\(op)\t\(args)\t\(result)")
    }

    static func f(_ v: Double) -> String {
        let s = String(format: "%.6f", v)
        return s == "-0.000000" ? "0.000000" : s
    }
    /// Inputs pass through this before the machine sees them, so the six decimals
    /// printed are exactly the value computed with. Without it, Double(i) / 30 is
    /// fed in full and printed rounded, and the Kotlin side replays the rounded
    /// number against a different answer.
    static func q(_ v: Double) -> Double { (v * 1e6).rounded() / 1e6 }
    static func pt(_ p: CGPoint) -> String { "\(f(p.x)),\(f(p.y))" }
}
