package com.roomlink.protocol

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import org.junit.jupiter.api.fail
import java.io.File
import java.math.BigDecimal
import java.math.RoundingMode

/**
 * protocol/transcripts.txt is generated by driving the Swift state machines
 * through scripted scenarios and recording every answer. This replays the same
 * inputs against the Kotlin machines and insists on the same answers, character
 * for character.
 *
 * The scenarios are not re-scripted here. That is the point: the vectors test
 * has to duplicate every construction in both languages and trusts the two
 * lists to be the same list; this reads the inputs off the file. One set of
 * scenarios, one owner (the file), and a port cannot pass by testing something
 * subtly different from what Swift tested.
 *
 * Numbers compare at six decimals. Both sides are IEEE binary64 doing the same
 * operations in the same order, so a difference at that precision is logic —
 * a threshold moved, a comparison flipped — not rounding.
 */
class TranscriptsTest {

    @TestFactory
    fun transcripts(): List<DynamicTest> {
        val file = File(System.getProperty("transcripts") ?: "../../protocol/transcripts.txt")
        assertTrue(file.isFile, "transcripts.txt not found at ${file.absolutePath}")

        val rows = file.readLines().filter { it.isNotBlank() && !it.startsWith("#") }.map { line ->
            val f = line.split("\t")
            assertEquals(5, f.size, "malformed transcript line: $line")
            Row(f[0], f[1], f[2], f[3], f[4], line)
        }
        // A short read must fail loudly rather than pass over half the machines.
        assertEquals(195, rows.size, "expected 195 steps, parsed ${rows.size}")
        assertEquals(
            setOf("chaingate", "pacer", "cursor", "pointer", "touch"), rows.map { it.machine }.toSet(),
            "every machine must appear — a missing one is an unported file",
        )

        // One test per scenario, replayed in order on a fresh instance.
        return rows.groupBy { it.machine to it.scenario }.map { (key, steps) ->
            DynamicTest.dynamicTest("${key.first} / ${key.second}") {
                val replay = replayer(key.first)
                for (s in steps) {
                    val actual = replay.step(s.op, args(s.args))
                    assertEquals(s.expected, actual, "${s.machine}/${s.scenario}  ${s.op} ${s.args}\n  line: ${s.line}")
                }
            }
        }
    }

    private data class Row(val machine: String, val scenario: String, val op: String, val args: String, val expected: String, val line: String)

    private fun args(s: String): Map<String, String> =
        if (s == "-") emptyMap() else s.split(" ").associate { kv -> kv.substringBefore("=") to kv.substringAfter("=") }

    private fun replayer(machine: String): Replayer = when (machine) {
        "chaingate" -> ChainGateReplay()
        "pacer" -> PacerReplay()
        "cursor" -> CursorReplay()
        "pointer" -> PointerReplay()
        "touch" -> TouchReplay()
        else -> fail("no replayer for machine '$machine'")
    }

    private interface Replayer { fun step(op: String, a: Map<String, String>): String }

    private class ChainGateReplay : Replayer {
        val g = ChainGate()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> {
                val v = g.admit(a.u16("seq"), a.u16("base"), a.flag("droppable"), a.flag("restores"))
                "${verdict(v)} ${state()}"
            }
            "reset" -> { g.reset(); state() }
            else -> fail("chaingate: unknown op $op")
        }
        fun state() = "broken=${g.isBroken.bit} missing=${g.missing} missingBase=${g.missingBase}"
        fun verdict(v: ChainGate.Verdict) = when (v) {
            ChainGate.Verdict.DECODE -> "decode"; ChainGate.Verdict.BROKEN -> "broken"; ChainGate.Verdict.STALE -> "stale"
        }
    }

    private class PacerReplay : Replayer {
        val p = Pacer()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> {
                val (v, late) = p.admit(a.d("remote"), a.d("now"))
                val vs = when (v) {
                    is Pacer.Verdict.Present -> "present:${f(v.after)}"
                    Pacer.Verdict.ShowNow -> "showNow"
                    Pacer.Verdict.DecodeOnly -> "decodeOnly"
                }
                "$vs late=${f(late)}"
            }
            else -> fail("pacer: unknown op $op")
        }
    }

    private class CursorReplay : Replayer {
        val c = CursorTrack()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "arrived" -> { c.arrived(a.u32("sentMs"), Point(a.d("x"), a.d("y")), a.d("now")); "-" }
            "position" -> c.position(a.d("now"))?.let { pt(it) } ?: "nil"
            "idle" -> c.idle(a.d("now")).toString()
            "isEmpty" -> c.isEmpty.toString()
            "clear" -> { c.clear(); "-" }
            else -> fail("cursor: unknown op $op")
        }
    }

    private class PointerReplay : Replayer {
        val p = PointerState()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> actions(p.admit(a.u8("buttons"), Point(a.d("x"), a.d("y")), a.d("now")))
            "release" -> actions(p.release(a.d("now")))
            else -> fail("pointer: unknown op $op")
        }
        fun button(b: PointerState.Button) = if (b == PointerState.Button.LEFT) "left" else "right"
        fun actions(out: List<PointerState.Action>) =
            if (out.isEmpty()) "-" else out.joinToString(";") {
                when (it) {
                    is PointerState.Action.Move -> "move(${pt(it.at)})"
                    is PointerState.Action.Drag -> "drag(${pt(it.at)},${button(it.button)})"
                    is PointerState.Action.Down -> "down(${pt(it.at)},${button(it.button)},${it.clicks})"
                    is PointerState.Action.Up -> "up(${pt(it.at)},${button(it.button)},${it.clicks})"
                }
            }
    }

    private class TouchReplay : Replayer {
        val t = TouchIntent()
        override fun step(op: String, a: Map<String, String>) = when (op) {
            "admit" -> steps(t.admit(phase(a.getValue("phase")), Point(a.d("x"), a.d("y"))))
            "holdFired" -> steps(t.holdFired())
            "awaitingHold" -> t.awaitingHold.toString()
            else -> fail("touch: unknown op $op")
        }
        fun phase(s: String) = when (s) {
            "began" -> TouchIntent.Phase.BEGAN; "moved" -> TouchIntent.Phase.MOVED
            "ended" -> TouchIntent.Phase.ENDED; "cancelled" -> TouchIntent.Phase.CANCELLED
            else -> fail("touch: unknown phase $s")
        }
        fun steps(out: List<TouchIntent.Step>) =
            if (out.isEmpty()) "-" else out.joinToString(";") { "step(${it.buttons},${pt(it.at)})" }
    }

    private companion object {
        /**
         * Six decimals, rounded half-even on the exact binary value — which is
         * what C's printf does on the Swift side. String.format would round
         * half-up on a decimal approximation instead; the two agree on every
         * value in the file today and would disagree on an exact tie tomorrow.
         */
        fun f(v: Double): String = BigDecimal(v).setScale(6, RoundingMode.HALF_EVEN).toPlainString()
        fun pt(p: Point) = "${f(p.x)},${f(p.y)}"
        val Boolean.bit get() = if (this) 1 else 0
        fun Map<String, String>.d(k: String) = getValue(k).toDouble()
        fun Map<String, String>.u8(k: String) = getValue(k).toUByte()
        fun Map<String, String>.u16(k: String) = getValue(k).toUShort()
        fun Map<String, String>.u32(k: String) = getValue(k).toUInt()
        fun Map<String, String>.flag(k: String) = getValue(k) == "1"
    }
}
